// DO NOT EDIT THIS FILE, EDIT THE WEBPACK COMMON CONFIG INSTEAD, WHICH WILL MODIFY THIS FILE
let _VERSION = '0.0.0'; // This value will be overwritten by webpack
let _DEBUG_INFO_ENABLED = true; // This value will be overwritten by webpack
/* @toreplace VERSION */
/* @toreplace DEBUG_INFO_ENABLED */
export const VERSION = _VERSION;
export const DEBUG_INFO_ENABLED = _DEBUG_INFO_ENABLED;

 export const API_URL = 'http://localhost:8080/web'; // 本地环境


export const FILE_URL = 'http://localhost:8080/web'; //档案管理系统专网分布式文件URL

export const FILE_UPLOAD_URL = FILE_URL + '/Files/'
export const IMAGES_UPLOAD_URL = FILE_URL + '/Images/'

window['UEDITOR_HOME_URL'] = API_URL; // UEditor配置

export const DITU_SERVER_URL = 'http://webrd03.is.autonavi.com/appmaptile?x={x}&y={y}&z={z}&lang=zh_cn&size=1&scale=1&style=8'; //高德地图

export const GEO_SERVER = ''; // 河长制GEO server